name: ghactivities Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build ghactivities Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            asset_name: ghactivities-linux-amd64
          - goos: darwin
            goarch: amd64
            asset_name: ghactivities-darwin-amd64
          - goos: darwin
            goarch: arm64
            asset_name: ghactivities-darwin-arm64
          - goos: windows
            goarch: amd64
            asset_name: ghactivities-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...

      - name: Build ghactivities binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -trimpath -ldflags="-s -w" -o ./dist/${{ matrix.asset_name }} ./cmd/ghactivities

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ./dist/${{ matrix.asset_name }}
